### ISSUE TITLE
Add the metods to take in account on other target's altitude onto plot

### ISSUE THREAD

**Issue by o-murphy** [o-murphy/py_ballisticcalc#34]

**Comment by dbookstaber** [comment]
Just made pull request https://github.com/o-murphy/py_ballisticcalc/pull/37

**Comment by dbookstaber** [comment]
The parameters we should associate with the weapon are (A) `sight_height` and (B) `zero_elevation`, which is the barrel elevation relative to the sight line when the sight is zeroed.  (Note that to _establish_ the zero_elevation the shooter has to be able to say what the point of impact is for one specific shot at one specific distance.  Typically this is done on a controlled range, so look_angle = 0.  With sights that support one-shot zero it can be done in the field so it can be necessary to incorporate the look-angle in that case.  But in every case that's a characteristic of the shot that established the zero, not the weapon setup.)

Then characteristics associated with a shot are:

- `look_angle` – which is the angle of the sight line relative to horizontal
- `relative_angle` – which is an adjustment of the barrel angle relative to the `zero_elevation` caused by shooter holding or dialing the sight relative to its zero.

Then the `barrel_elevation` for the shot `= zero_elevation + relative_angle + look_angle`

**Comment by dbookstaber** [comment]
TODO: Need to review trajectory_calc::wind_to_vector().  Not sure if that is taking all angles into account correctly – even before recent changes.

**Comment by dbookstaber** [comment]
Just pushed new branch with first pass at this refactoring: https://github.com/dbookstaber/py_ballistics/tree/refactor_angles

**Comment by o-murphy** [comment]
I have to review it, so I'll do it next week
